image: gitpod/workspace-full:2023-02-27-14-39-56
tasks:
  - name: install-dependencies
    before: |
      printf 'export PATH="$HOME%s:$PATH"\n' "/.astra/cli" >> $HOME/.bashrc
      printf 'unset JAVA_TOOL_OPTIONS\n' >> $HOME/.bashrc
      curl -Ls "https://dtsx.io/get-astra-cli" | bash >> ./install.log
      printf 'export PATH="$GITPOD_REPO_ROOT%s:$PATH"\n' "/cassandra3/bin" >> $HOME/.bashrc
      printf 'export PATH="$GITPOD_REPO_ROOT%s:$PATH"\n' "/cassandra3/tools/bin" >> $HOME/.bashrc
    init: |  
      yes | sdk install java 8.0.345.fx-zulu
      wget https://archive.apache.org/dist/cassandra/3.11.16/apache-cassandra-3.11.16-bin.tar.gz
      pip install -U cqlsh
    command: | 
      tar -xzf apache-cassandra-3.11.16-bin.tar.gz
      rm apache-cassandra-3.11.16-bin.tar.gz
      mv apache-cassandra-3.11.16 cassandra3
      source /home/gitpod/.astra/cli/astra-init.sh
      cassandra3/bin/cassandra
ports:
  - port: 9042
    onOpen: ignore
  - port: 7000
    onOpen: ignore
  - port: 7199
    onOpen: ignore 
github:
  prebuilds:
    main: true
vscode:
   extensions:
    - https://github.com/DataStax-Academy/katapod/releases/download/stable/katapod-stable.vsix

